### ISSUE TITLE
Cannot hear audio from Cider with Discord screen share

### ISSUE THREAD

**Issue by ReallyUnusual** [ciderapp/Cider-2#471] opened 2023-12-18 01:10 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Version 2.12.6 (9/17/2023)

### Operating System Version

Windows 10 version 22H2

### Describe the Bug

I'm screen-sharing Cider on Discord, but I can't hear audio from Cider through the Discord screen share. I noticed that "Microsoft Edge WebView2" is the audio for Cider, but Discord doesn't pick it up.

### Steps to Reproduce

1. Screen share Cider on Discord
2. Watch the stream
3. Able to see the stream, but not hear audio from it

**Comment by coredev-uk** [comment] 2023-12-18 01:44
duplicate of #220. please make sure to check closed issues before opening ones

**Closed by coredev-uk** 2023-12-18 01:44 UTC
Labels: 🐛 Bug
