### ISSUE TITLE
Window size is NOT saving session-to-session

### ISSUE THREAD

**Issue by lindros2** [ciderapp/Cider-2#593] opened 2024-03-27 14:01 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

e2c4453f1234558822d2ea7b764dc0d43a05813c

### Connect Instance ID

not-logged-in

### Build Timestamp

3/22/2024, 7:23:49 PM

### Describe the Bug

Window size is NOT saving session-to-session

### Steps to Reproduce

1. Resize (or maximize) window
2. Exit
3. Restart

**Comment by coredev-uk** [comment] 2024-06-19 00:41
Being fixed with dotnet build, should be fixed with 2.5.0

**Closed by coredev-uk** 2024-06-19 00:41 UTC
Labels: bug, windows

**Comment by lindros2** [comment] 2024-07-26 12:55
When will Cider 2.5 be available?
I've now paid for three versions, and I'm stuck on 2.4, with the crap
window.

**Comment by coredev-uk** [comment] 2024-07-26 13:09
I cant say, if you really want early access to 2.5 you can get it with the Alpha builds through donating·

**Comment by lindros2** [comment] 2024-07-26 14:19
But I paid - twice in a short period of time - what else can I “donate”? This seems like a slimy money grab On Jul 26, 2024, at 9:10 AM, Core ***@***.***> wrote:﻿
I cant say, if you really want early access to 2.5 you can get it with the Alpha builds through donating.

**Comment by coredev-uk** [comment] 2024-07-26 14:23
You paid twice?

**Comment by coredev-uk** [comment] 2024-07-26 14:25
This is not a money grab, this has always been this case. There has always been itch, Microsoft Store and donator channels. If you purchased the wrong package that is on you, it is clearly stated on our website which packages are available and that donator channels can get early access to upcoming releases. 2.5 is a big release this is the reason why it is taking so long.

**Comment by lindros2** [comment] 2024-07-26 14:36
I paid twice - I bought one version, then it was EOL less than a month
later.
So I paid again, to get Cider 2.

**Comment by coredev-uk** [comment] 2024-07-27 15:09
Paying for Cider 1 was never a requirement. The project was open-sourced and builds were available for all platforms for free.

**Comment by cryptofyre** [comment] 2024-07-27 15:30
^ Chiming on this to say that we've offered free migration for paid C1 users on the Microsoft Store to obtain free copies of C2 additionally.

**Comment by lindros2** [comment] 2024-07-27 16:28
Untrue and enough.
I tried to switch many times and got stonewalled, resulting in a "re-buy"
weeks after the initial v1 was EOL.
As an open source contributor I've *never* in my life dealt with such
combative pushback. Ever.

In summary, the app is unusable since 1) it logs out frequently, and 2)
window size issue (regression?) has taken forever to fix.
This project and its contributors make me hope your libraries get
compromised so you have to scramble to fix issues instead of battling
people who paid for this.

**Comment by cryptofyre** [comment] 2024-07-27 16:34
You should've gotten in contact, we would've helped you? I don't know why you're being so aggressive about this, this is not pushback at all. We're just offering details that you may have missed evidently.

**Comment by cryptofyre** [comment] 2024-07-27 16:38
Cider 2.x is an entire app rewrite and isn't really capable of having as you call "regressions" because it is functionally entirely different and shares little to no app commodities with its original counterpart.

As for constantly having to login, you probably just have a corrupt config file due to an improper shutdown or otherwise. It happens, and its easy to fix. You really don't need to attack us so aggressively over things like that, it's not like we have full documentation to whats going on for Apple's side of things either.

There are much better ways to handle such situations than hoping that their "libraries get compromised" and that we scramble to fix things. This is incredibly immature.

**Comment by cryptofyre** [comment] 2024-07-27 16:43
Regardless, all your issues will have or would've been fixed in the 2.5.x update as that brings a newer backend that can actually work with what you want.

Previously we tried using an experimental Rust backend (Tauri) and it lacked several features in proper implementation so while I can't speak on their behalf, I offer a sorry that we couldn't implement such features and im sorry our other developers threw another "stonewall" at your with a donation payment (which you can totally ignore and I probably would've helped you work around, but thats out the window now) but the update isn't quite ready for consumer use or we experience a lot of general community outrage when things don't work.

We've since made our own backend using C# that allows us to do a lot more with what you want such as taskbar buttons, task tray icon, window state persistence, and various other things.

![2JCfufr0c7](https://github.com/user-attachments/assets/492d4cd9-2066-4b39-ae8d-b8f349044ee5)

**Comment by lindros2** [comment] 2024-07-27 16:47
I tried getting in touch but there was no where to "get in touch". I went
everywhere and had no way to "get in touch" until my bug report was
acknowledged and the fix was put in for 2.5.
I recognize it's not commercial, appreciate the effort, but this isn't the
way open source communities are supposed to work.
Let's end this thread - everyone getting angry and I'm disappointed.

**Comment by cryptofyre** [comment] 2024-07-27 16:52
Next time if you have an app breaking issue feel free to contact us on either Discord (https://discord.gg/applemusic) or even my organizational email at cryptofyre@cider.sh.

I appreciate the request to defuse the situation, and I do agree its best we all take a step back here.
