### ISSUE TITLE
Crash on Linux on maximize (Gnome)

### ISSUE THREAD

**Issue by LauraWebdev** [ciderapp/Cider-2#767] opened 2024-09-12 07:41 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Nobara (Fedora 40)

### Commit Hash

197927c6fe8970abaaad9b481efb3b69e71685e0

### Describe the Bug

This has happened for a few weeks now. Whenever I want to maximize the application window, whether it's via the button or by dragging it to the top of the screen OR I want to restore the window to non-maximized, the application crashes after a second without redrawing the page content.

### Steps to Reproduce

1. Open Cider
2. Drag it to the top of the screen or use the button to maximize
3. This will crash client
4. Reopen, it is now maximized
5. Drag the titlebar from the top or use the button to restore
6. This will also crash

### Anything else?

A screenshot of the client right before crashing.

![image](https://github.com/user-attachments/assets/9ad74fce-b909-47ba-a7d9-0ee4ad3a2d1a)

**Comment by coredev-uk** [comment] 2024-09-20 00:26
Duplicate of #681

**Closed by coredev-uk** 2024-09-20 00:26 UTC
Labels: bug
