### ISSUE TITLE
[Bug]: UI bug when using light mode

### ISSUE THREAD

**Issue by maxwiseman** [ciderapp/Cider-2#174] opened 2023-05-03 01:31 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

V2.0.2

### Operating System Version

Windows 11 Pro 22H2 (build 22621.1555)

### Describe the Bug

I use light mode in Windows, and although there is no light mode in Cider (which there should be), after being open for a while, the background changes to the light mica color. This is an issue because the white text is practically invisible.

### Steps to Reproduce

1. Switch to light mode in Windows settings
2. Open Cider
3. Minimize it or go to immersive mode (I don't know if you have to do this, but I have only seen this issue occur when I do)
4. Wait for a while (could be up to a few hours)
5. Focus Cider again or exit immersive mode

Note: The time seems to be relative to when the app was opened not to when the app was last focused.

### Anything else?

![image](https://user-images.githubusercontent.com/60909484/235817395-b04b15c9-089b-47ce-97fe-f8537f3213f9.png)
(Background is the light mica material, it's just green because my wallpaper is green, when I focus another window it turns white)

### Build timestamp

5/1/2023

**Comment by coredev-uk** [comment] 2024-01-10 17:35
Duplicate of #188

**Closed by coredev-uk** 2024-01-10 17:35 UTC
Labels: 🐛 Bug, 👥 team: frontend
