### ISSUE TITLE
[Bug]: Full Screen in Immersive Mode not working as expected

### ISSUE THREAD

**Issue by jeleddddd** [ciderapp/Cider-2#235] opened 2023-06-07 03:24 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

17/05/2023, 1:25:48 pm Quasar v2.11.10

### Operating System Version

Windows 11 Version 22H2

### Describe the Bug

The immersive mode full screen did not hide the taskbar together.
![image](https://github.com/ciderapp/Cider-2/assets/135791981/ceafc1a5-874b-451d-a10a-ba95eaa45ab3)

### Steps to Reproduce

Click on full screen in immersive mode when maximizing Cider

### Build timestamp

1686107958541

**Comment by sethbrown321** [comment] 2023-06-14 00:13
Same thing here, but it's completely obvious...
![Screenshot 2023-06-13 201231](https://github.com/ciderapp/Cider-2/assets/46170382/57f746c0-dcba-4a9e-b47f-bfa150c3e494)

**Comment by cryptofyre** [comment] 2023-06-14 00:23
This is a known issue, although there isn't a whole lot we can do about due to how Windows compositing is handled. You can mitigate this by making sure the app is not maximized before entering fullscreen.

**Comment by coredev-uk** [comment] 2023-06-21 03:04
Duplicate of https://github.com/ciderapp/Cider-2/issues/155

**Closed by coredev-uk** 2023-06-21 03:04 UTC
Labels: 🐛 Bug
