### ISSUE TITLE
Navbar smear when scrolling

### ISSUE THREAD

**Issue by Amadej99** [ciderapp/Cider-2#592] opened 2024-03-26 08:31 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

e2c4453f1234558822d2ea7b764dc0d43a05813c

### Connect Instance ID

not-logged-in

### Build Timestamp

23/03/2024, 00:23:49

### Describe the Bug

Smearing when scrolling the navigation tab.

![image](https://github.com/ciderapp/Cider-2/assets/65547562/bf6dbdaa-9ae5-4602-855e-580dd51250b8)

### Steps to Reproduce

1. Open the Cider app.
2. Scroll on the navbar.

**Comment by coredev-uk** [comment] 2024-03-28 13:34
Turn off HDR, which tends to cause these issues.

**Comment by coredev-uk** [comment] 2024-03-28 13:45
Also gonna mark this as a duplicate of https://github.com/ciderapp/Cider-2/issues/585

**Closed by coredev-uk** 2024-03-28 13:45 UTC
Labels: bug
