### ISSUE TITLE
[Bug]: Saki AI chatBot doesn't work?

### ISSUE THREAD

**Issue by Owenfly** [ciderapp/Cider-2#141] opened 2023-04-15 14:15 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

2023.4.10

### Operating System Version

Windows 11 22H2

### Describe the Bug

 Saki AI chatBot  can only have two conversations in a row, and then it won't respond

### Steps to Reproduce

1、使用chatbot
2、问了两次后就没办法继续进行下去了

### Anything else?

![image](https://user-images.githubusercontent.com/55825205/232229811-0f0be4b7-2fe1-45f5-ba27-b9700302a533.png)

**Comment by coredev-uk** [comment] 2023-04-15 14:18
Wgat

**Comment by Owenfly** [comment] 2023-04-15 16:09
> what

Each time I use it, it will only answer twice, and then it will not answer. I don't know if it is affected by network factors.

**Comment by coredev-uk** [comment] 2023-04-17 23:47
Can you please give the issue in English, specifically the steps to reproduce

**Comment by Owenfly** [comment] 2023-04-18 01:13
![image](https://user-images.githubusercontent.com/55825205/232643335-0aed6b54-0b87-42d2-83b3-8293b5af6497.png)
Sure. Firstly,I click the button 'Saki ai', Then after two rounds of dialogue, it doesn't work. look this picture

**Comment by Amaru8** [comment] 2023-10-04 13:48
Hey there! I couldn't reproduce this on [version 2.2.0](https://outline.cider.sh/s/2-2-0-changelog), so I'm assuming that a fix has been issued for this since May 31. Closing.

**Closed by Amaru8** 2023-10-04 13:48 UTC
Labels: 🐛 Bug, 🛠️ Triaged, 🤖 feat: Compose, 👥 team: connect
