### ISSUE TITLE
Volume slider

### ISSUE THREAD

**Issue by defaultunknown** [ciderapp/Cider-2#583] opened 2024-03-20 11:10 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [ ] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Microsoft Store

### Operating System

Windows 

### Commit Hash

6d28d866c04a05d34605ec0afe0ad387d608b01d

### Connect Instance ID

not-logged-in

### Build Timestamp

3/19/2024, 8:31:20 AM

### Describe the Bug

Slider not synced with mouse movement

### Steps to Reproduce

1. Launch cider2
2. start track
3. move volume slider to 100% and then move mouse with right click holded from right to left

**Comment by HalloTheEngineer** [comment] 2024-04-07 16:46
Can confirm it. Some sliders in the Cider 2 app scale incorrectly.

https://github.com/ciderapp/Cider-2/assets/83722147/4755b8e7-dd57-42fd-88cb-2ef0220a2827

**Comment by HalloTheEngineer** [comment] 2024-05-07 14:50
Still not fixed in v2.4.0_0 of the Cider 2 client.

**Comment by cryptofyre** [comment] 2024-05-07 15:24
Intended behavior, not a bug. Set a different volume bar style in the advanced tweaks menu.

**Closed** 2024-05-07 15:24 UTC
Labels: wont fix
