### ISSUE TITLE
Suggested songs bug.

### ISSUE THREAD

**Issue by looking4freedom** [ciderapp/Cider-2#623] opened 2024-05-04 21:17 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

618b467d19eab9fc0bb786c2efb1c04f7a52ed96

### Connect Instance ID

not-logged-in

### Build Timestamp

4/4/2024, 4:01:00

### Describe the Bug

When i look for songs at the bottom of the page in ''suggested songs'' , it start bugging and the preview audio from that song stops playing , i have  to restart cider to fix it. 

### Steps to Reproduce

Entering on my playlist then scrolling all the way down til u reach ''suggested songs''. Then play some of them and refresh for new songs. The audio of the preview will stop playing with the time.

**Comment by cryptofyre** [comment] 2024-05-08 03:18
Intended behavior(?) or issue is not explained clearly enough. Song previews are supposed to stop when you refresh for new ones as that UI element is no longer available.

Closing.

**Closed by cryptofyre** 2024-05-08 03:18 UTC
Labels: bug
