### ISSUE TITLE
Wrong artwork for MP3 files

### ISSUE THREAD

**Issue by justinsijbolts** [ciderapp/Cider-2#711] opened 2024-08-16 07:25 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

itch

### Operating System

macOS Sonoma (14.4.1)

### Describe the Bug

It's possible to add MP3 files to Apple Music through the AM for macOS app. Doing so will also make them show up on iPhone and Cider. Unfortunately, Cider doesn't really seem to handle these files particularly well. (E.g. buttons like 'Go to Artist' are there, but don't do anything)

The biggest issue I have however is the fact that the shown artwork is the artwork of the song that was last played that DID have artwork.

![image](https://github.com/user-attachments/assets/5976c21b-0cc2-4f96-8806-b680e4909670)

The cover art shown here is a song I've previously listened to that did have cover art, I think a fix would be showing like a '?' icon (like how it shows on actual AM).

### Steps to Reproduce

1. Add an MP3 file to your Apple Music library through the regular AM client
2. Play it through Cider
3. Take a peek at the broken cover art :)

### Anything else?

Shown cover art on the regular AM client on Mac:
![image](https://github.com/user-attachments/assets/140ead9e-164b-4b66-b1ec-8a36a3343163)

**Comment by coredev-uk** [comment] 2024-11-25 06:47
Please try the latest experimental build from [taproom](https://taproom.cider.sh) and confirm if the issue is no longer present.

**Comment by justinsijbolts** [comment] 2024-11-25 09:13
I have confirmed that this issue is **still present** in the latest Experimental build as of November 25.

**Comment by coredev-uk** [comment] 2024-12-01 02:20
Fixed in https://github.com/ciderapp/citadel/commit/f8c187cde4bf5fef070a710efa120d6742cb3555
Should be available in the next experimental release, or in stable later this month.

**Closed by coredev-uk** 2024-12-01 02:20 UTC
Labels: bug, status/confirmed, frontend
