### ISSUE TITLE
[Bug]: Playlists won't show even after refreshing

### ISSUE THREAD

**Issue by Thedinotamer** [ciderapp/Cider-2#519] opened 2024-02-06 11:40 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

Built on 2024-02-02 00:48:07 | Quasar 2.14.2 | Sabiiro 04cd30afc5c14d26f05ecc117ca027d7adea8b8c

### Operating System Version

Windows 10 Home 22H2 Version 19045.3930

### Describe the Bug

When I uninstalled the last version and then installed 2.3.0, downloaded through itch.io, the playlists won't show even with "Use Experimental Playlist Retrieval Method" enabled and refresh afterwards.

### Steps to Reproduce

1. uninstall last version via revo uninstaller with advanced mode
2. download 2.3.0 on itch.io
3. install 2.3.0
4. result

### Anything else?

![Skärmbild 2024-02-06 123635](https://github.com/ciderapp/Cider-2/assets/20649872/490ff0fe-0fdb-4e31-9c97-476da4cdd6b9)
![Skärmbild 2024-02-06 123745](https://github.com/ciderapp/Cider-2/assets/20649872/f43e090c-43f5-41e1-8070-b2be6a764c66)
![Skärmbild 2024-02-06 123812](https://github.com/ciderapp/Cider-2/assets/20649872/f81353df-8884-49d3-b00d-96bbe6ea7b1a)
There's supposed to be a playlist there called "Favoriter" too, but it only shows "All playlists"

### Build timestamp

1707217958905

**Comment by cryptofyre** [comment] 2024-02-06 12:18
Duplicate of #488, Upgrade to the latest pre-release version in the update manager.

**Closed by cryptofyre** 2024-02-06 12:18 UTC
Labels: 🐛 Bug
