### ISSUE TITLE
[Bug]: Unable to login to Last.Fm

### ISSUE THREAD

**Issue by slesleslet** [ciderapp/Cider-2#529] opened 2024-02-11 00:14 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

today

### Operating System Version

windows 11 version 22H2

### Describe the Bug

Scroobling in last.fm doesn't work

### Steps to Reproduce

I just linked the accounts and it doesn't work

### Build timestamp

1707610060537

**Comment by DiscordianEris** [comment] 2024-02-14 01:03
I have experienced the same problem.  If it is any help this is the window that appears after I try to link Cider to the last.fm Applications. 

![image](https://github.com/ciderapp/Cider-2/assets/159965405/9ba7d87b-d2f6-4975-87dc-7fa7f7ab6ca7)

**Comment by coredev-uk** [comment] 2024-02-15 10:28
Think tauri is blocking it or smth

**Comment by coredev-uk** [comment] 2024-02-15 10:30
duplicate of #524

**Closed by coredev-uk** 2024-02-15 10:30 UTC
Labels: 🐛 Bug
