### ISSUE TITLE
Animated Artwork is not rounded in album view

### ISSUE THREAD

**Issue by UnbreakCode** [ciderapp/Cider-2#487] opened 2024-01-15 13:24 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.3.0 RC 12

### Operating System Version

Windows 11

### Describe the Bug

The animated artwork is not rounded in the album view.
https://music.apple.com/de/playlist/deutschrap-chill/pl.c0c96a527a49494588e32e635016f5ee
![image](https://github.com/ciderapp/Cider-2/assets/34512773/b7d171f9-0503-4cff-963a-f7ea8afcb84b)

### Steps to Reproduce

1. Open Playlist "Deutschrap Chill" -> https://music.apple.com/de/playlist/deutschrap-chill/pl.c0c96a527a49494588e32e635016f5ee

**Comment by booploops** [comment] 2024-01-18 02:52
Currently an intended behavior as the playlist page is being further developed in the RC.  This is something that will be resolved in a future build.

**Closed** 2024-01-30 13:45 UTC
Labels: 🐛 Bug, 🛠️ Triaged
