### ISSUE TITLE
Unable to pause radio streams

### ISSUE THREAD

**Issue by MiniMadcraft** [ciderapp/Cider-2#626] opened 2024-05-07 15:16 UTC
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Windows 

### Commit Hash

7d5564d9a035b91d9a09a1eab3f19477f3ffe18e

### Connect Instance ID

not-logged-in

### Build Timestamp

03/05/2024, 19:35:13

### Describe the Bug

Since updating to the latest version (2.4.0), I have been unable to pause live radio streams. I was able to do so in 2.3.2 and earlier versions, where upon unpausing it automatically catches back up.

### Steps to Reproduce

Play the Apple Music One / Hits / any "live" radio stations and press pause, nothing happens.

**Comment by coredev-uk** [comment] 2024-06-19 00:59
Duplicate of https://github.com/ciderapp/Cider-2/issues/612

**Closed by coredev-uk** 2024-06-19 00:59 UTC
Labels: bug, duplicate, frontend
