### ISSUE TITLE
[Bug]: When opening the app, playlists don't load completely

### ISSUE THREAD

**Issue by chispito** [ciderapp/Cider-2#567] opened 2024-03-08 07:17 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that I am using a supported version of Cider. You can find the list of supported versions [here](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md).
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).

### What operating system are you using?

Windows

### Build Details

2.3.2.0-RC1 | Built on 2/3/2024, 2:00:40 | Sabiiro | 18cc5a2d67829e4d5e5bd3b479aa22d68e5a68bb

### Operating System Version

Windows 11

### Describe the Bug

Hi there! It has happened to me before, not all the playlists load, exactly like last time. It happens to both Apple playlists and mine.
I tried signing out and in from my Apple account, but it doesn't help, they just don't load.

Please help!
Thanks!

Teddy

### Steps to Reproduce

Nothing special, just open the app...

### Build timestamp

1709881845467

**Comment by behoward** [comment] 2024-03-09 22:37
i have the same problem.  It shows only roughly the first 50 or so playlists in each of "Apple" and personal playlists sections

**Comment by cryptofyre** [comment] 2024-03-16 11:15
Duplicate of #573, closing.

**Closed by cryptofyre** 2024-03-16 11:15 UTC
Labels: bug
