### ISSUE TITLE
Can not sign in with apple music

### ISSUE THREAD

**Issue by IWANTFREESHIT** [ciderapp/Cider-2#634] opened 2024-05-09 00:24 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

itch

### Operating System

Windows 

### Commit Hash

7d5564d9a035b91d9a09a1eab3f19477f3ffe18e

### Connect Instance ID

not-logged-in

### Build Timestamp

5/3/2024, 1:35:13 PM

### Describe the Bug

use to be able to log in with apple music, now button does nothing

### Steps to Reproduce

!. launch cider
2. click sign into apple music

### Anything else?

can i have my 4 dollars back

**Comment by cryptofyre** [comment] 2024-05-09 00:42
Duplicate of #633, don't worry we're fixing it.

**Closed** 2024-05-09 00:42 UTC
Labels: bug
