### ISSUE TITLE
[Bug]: Discord Rich Presence not working on Linux

### ISSUE THREAD

**Issue by rthwldn** [ciderapp/Cider-2#319] opened 2023-08-07 22:05 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Linux

### Build Details

7/22/2023, 1:13:44 PM

### Operating System Version

Pop!_OS 22.04 LTS x86_64 

### Describe the Bug

Nothing will display in my Discord profile. In Cider I tried everything I even tried different installators and versions of Discord (PBT, Canary, Pop Store, .deb) and it still didn't work. Already tried logging out, restart Cider, Discord and computer.

![Screenshot from 2023-08-07 23-49-51](https://github.com/ciderapp/Cider-2/assets/141244942/60a56686-8b8e-4942-a58a-f081fd53e023)
![Screenshot from 2023-08-07 23-50-02](https://github.com/ciderapp/Cider-2/assets/141244942/34cb8303-ad08-4900-b6bd-1286f4981344)
![Screenshot from 2023-08-08 00-04-01](https://github.com/ciderapp/Cider-2/assets/141244942/fd041f1b-9107-4c2c-b0c5-a1de00dfd4aa)

### Steps to Reproduce

It just doesn't work.

### Connect Device ID

jpsJtePs4vgbin9Vyfdkie6RvRo1

### Build timestamp

1691445713555

**Comment by alsoGAMER** [comment] 2023-09-16 08:36
``` js
Error: Could not connect
    at Socket.onerror (/app/cider/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

According to discord-rpc's documentation, this exception is thrown when the library can't find the ipc file on the system, which is odd considering that it's present and other apps (like premid) can connect to it completely fine... maybe it doesn't like symlinks?

```lrwxrwxrwx  1 alsog alsog  61 set 16 01:24 discord-ipc-0 -> /run/user/1000/app/com.discordapp.DiscordCanary/discord-ipc-0```

**Comment by cryptofyre** [comment] 2023-09-16 19:21
Are you using Discord over Flatpak?

**Comment by alsoGAMER** [comment] 2023-09-16 19:23
Yes and Cider is running under flatpak too

**Comment by cryptofyre** [comment] 2023-09-18 01:53
Fixed in 2.2.0, please redownload it from Itch.io.

**Closed by cryptofyre** 2023-09-18 01:53 UTC
Labels: 🐛 Bug

**Comment by alsoGAMER** [comment] 2023-09-18 08:36
I'm already on 2.2.0 and the issue is still there

**Comment by cptn-cosmo** [comment] 2025-03-04 09:56
2.6.1.9 and still broken
