### ISSUE TITLE
Playback randomly stops for no reason and cannot be resumed

### ISSUE THREAD

**Issue by henryco** [ciderapp/Cider-2#639] opened 2024-05-15 00:08 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Itch

### Operating System

Linux 5.15.0-105-generic

### Commit Hash

247e299e8c3cfc440d9012dd50949e2679864dcb

### Connect Instance ID

not-logged-in

### Build Timestamp

5/9/2024, 2:57:55 AM

### Describe the Bug

Playback randomly stops for no reason, without any error message or anything else. Pressing play button to resume playback does not work in such case, you have to re-select song from playlist in order to make it play again.

### Steps to Reproduce

Nothing specific, error occurs

### Anything else?

[2024-05-15 01:54:58.858] [debug] [utils:api][scanFolders] Scanning folder. { id: 'p.playlistsroot', count: 6 }
[2024-05-15 01:55:02.197] [error] [utils:api][v3] Failed to fetch data. {
  call: {
    href: '/v1/me/favorites',
    args: { 'ids[songs]': '1451199171' },
    opts: { paramsInURL: true, fetchOptions: { method: 'POST' } }
  },
  error: 'Error: Unexpected end of JSON input\n' +
    '    at async gJ (http://localhost:9500/assets/index.a58ab4c1.js:98:90865)\n' +
    '    at async m (http://localhost:9500/assets/MediaItemContextMenu.751591c2.js:1:12282)'
}
[2024-05-15 01:55:16.268] [error] [utils:api][v3] Failed to fetch data. {
  call: {
    href: '/v1/me/favorites',
    args: { 'ids[playlists]': 'pl.1dc1be5fa0204ab1847ab5b2822955c3' },
    opts: { paramsInURL: true, fetchOptions: { method: 'POST' } }
  },
  error: 'Error: Unexpected end of JSON input\n' +
    '    at async gJ (http://localhost:9500/assets/index.a58ab4c1.js:98:90865)\n' +
    '    at async m (http://localhost:9500/assets/MediaItemContextMenu.751591c2.js:1:12282)'
}
[2024-05-15 01:57:51.998] [debug] [MusicKit][nowPlayingItemDidChange:fetchArtwork] MusicKit artwork https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/a4/cc/3e/a4cc3e29-b0fd-a3c1-96c7-a8ea84bdf082/4050486010723_cover.jpg/{w}x{h}bb.jpg
[2024-05-15 02:01:38.958] [debug] [MusicKit][nowPlayingItemDidChange:fetchArtwork] MusicKit artwork https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/a7/96/85/a7968552-0ebf-4124-3a08-c7a43dbe176f/3663729216908_cover.jpg/{w}x{h}bb.jpg
[2024-05-15 02:01:42.327] [debug] [MusicKit][mediaPlaybackError] Playback Error Error: loadSegmentError
[2024-05-15 02:02:04.087] [debug] [utils:api][fetchPlaylists] Fetching playlists.
[2024-05-15 02:02:04.470] [debug] [utils:api][scanFolders] Scanning folder. { id: 'p.playlistsroot', count: 6 }

**Comment by coredev-uk** [comment] 2024-06-19 00:57
Gonna mark this as a duplicate of https://github.com/ciderapp/Cider-2/issues/639

**Closed by coredev-uk** 2024-06-19 00:57 UTC
Labels: bug, duplicate, unreproducible, edge-case, frontend
