### ISSUE TITLE
Cider always uses secondary GPU

### ISSUE THREAD

**Issue by GreyAsteroid** [ciderapp/Cider-2#507] opened 2024-02-02 22:21 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

macOS

### Build Details

Cider 2.3.0, Quasar v2.14.3

### Operating System Version

macOS Sonoma 14.3 (23D56)

### Describe the Bug

I have a 2019 Mac Pro with 2 GPUs installed, a monitor is plugged into each GPU. Regardless of which monitor Cider is open on, the GPU process always runs on my secondary GPU. I've confirmed with `MTLCreateSystemDefaultDevice()` that the secondary GPU is **NOT** the default metal device.

### Steps to Reproduce

1. Have a defunct Intel Mac with PCIe slots
2. Have multiple GPUs installed in said machine
3. Have monitors plugged into said GPUs
4. Suffer

### Anything else?

![SCR-20240202-peho](https://github.com/ciderapp/Cider-2/assets/4615298/72d1a9be-1441-4fc6-9d4c-894f939609c8)
_Screenshot of Cider running on the display using the RX 580 with Activity Monitor showing the Cider GPU process running on the RX 560 and a terminal window showing the RX 580 as the default metal device._

This is a similar issue to https://github.com/ciderapp/Cider-2/issues/44 but it seems that was focused on Windows and was closed because of it's reliance on Tauri, that's not the case here so I've created a new issue.

**Comment by coredev-uk** [comment] 2024-02-06 15:27
Duplicate of https://github.com/ciderapp/Cider-2/issues/44

Electron doesn't allow the control either.

**Closed by coredev-uk** 2024-02-06 15:27 UTC
Labels: 🐛 Bug

**Comment by GreyAsteroid** [comment] 2024-02-06 15:51
> Duplicate of #44
> 
> Electron doesn't allow the control either.

Unfortunate but I understand. I should note though, it seems to only be a problem when ANGLE is using the default backend. If you start Cider with the `--use-angle=metal` flag then Cider will properly choose the GPU based on the active monitor and switch between them. Seems to be my workaround for now 😅.
