### ISSUE TITLE
[Bug]: Recently Played Section Showing "CloudFavoritesContainer.Name" Instead of "Favorite Songs"

### ISSUE THREAD

**Issue by TomDaamen** [ciderapp/Cider-2#578] opened 2024-03-16 20:56 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### What operating system are you using?

Windows

### Build Details

2.3.2.0 | Built on Invalid Date | Sabiiro | b68c3db21100bd6ed7e84420c10426717b568d72

### Operating System Version

Windows 11 Pro | Version: 23H2 | Build: 22631.3155 | Support: Windows Feature Experience Pack 1000.22684.1000.0

### Describe the Bug

Within the application's recently played section, the label or string appears as "CloudFavoritesContainer.Name" instead of the expected term "Favorites".

### Steps to Reproduce

1.     Open the application and navigate to the "Favorite Songs" playlist.
2.     Play the playlist.
3.     Restart the application (Cider).
4.     Look at the "Recently Played" section.

### Anything else?

My Guess: probably happens because the name or label in the code / interface wasn't assigned or referenced correctly or does not exist.

### Build timestamp

1710621352083

**Comment by coredev-uk** [comment] 2024-03-16 22:05
Duplicate of https://github.com/ciderapp/Cider-2/issues/534. Please read the comment I left on that post. Just to add to it, we do not directly set the text in app, we rely on data that their api gives us, as such this is a bug with the MusicKit API. If we were to directly set it, it would affect all languages and would not be practical. Sorry I cant help you more.

**Closed by coredev-uk** 2024-03-16 22:05 UTC
Labels: bug
