### ISSUE TITLE
Trying to acces the hamburger menu while searching for a song plays the song

### ISSUE THREAD

**Issue by Futinghe** [ciderapp/Cider-2#763] opened 2024-09-06 22:02 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Cider-2/issues) for a bug report that matches the one I want to file, without success.
- [X] I have checked that the correct behavior occurs on [Apple Music Web](https://music.apple.com) (if applicable).
- [X] I have verified that my issue is with a [supported version](https://github.com/ciderapp/Cider-2/blob/main/SECURITY.md) and that it is with the desktop app (Support for other areas can be found in our Discord / on the appropriate repo).

### Download Source

Discord

### Operating System

Windows 11

### Commit Hash

766652aa4212508de014b6233c338b6e9b41ff37

### Build Timestamp

1724117213706

### Describe the Bug

When searching for a song via the top search bar, trying to access the hamburger menu on any of the results acts like a normal click and plays the song/open the album or artist page.

### Steps to Reproduce

-Search for anything, for example "hotline bling"
-Click on the hamburger menu
-The song plays instead of the menu opening

https://github.com/user-attachments/assets/2e17ce77-b04b-4444-81cd-873e8398b089

**Comment by coredev-uk** [comment] 2024-09-08 16:12
Duplicate of #730

**Closed by coredev-uk** 2024-09-08 16:12 UTC
Labels: bug
